[package]
name = "aa-hal"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
embedded-hal = "1.0.0-alpha.9"
fixed = "1.20.0"
fugit = "0.3.6"
fugit-timer = "0.1.3"
nb = "1.0.0"
num-traits = "0.2.15"
ramp-maker = "0.2.0"
rppal = { version = "0.14", features = ["hal"] }
stepper = { git = "https://github.com/shyndman/hal-stepper" }
typenum = "1.15.0"
