[package]
name = "aa-foundation"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
indoc = "1.0.7"
tracing = "0.1"
tracing-subscriber = { version = "0.3.16", features = ["registry", "std", "env-filter"] }
