# Do not call `docker compose` on this file directly, as it needs work done
# beforehand to build the software correctly.
#
# The `Hakufile` in the workspace root has everything you're looking for.
services:
  aa_app:
    image: ${REGISTRY_ADDRESS}/arena-autocam/aa-app_${AA_BUILD_TARGET}_${AA_BUILD_PROFILE}:latest
    # Privileged is required so that we can access host devices
    privileged: true
    volumes:
      - /dev:/dev
    build:
      context: ".."
      dockerfile: aa_app/docker/Dockerfile
      # These args must be defined in each of the arch specific docker-compose
      # files
      args:
        - BUILD_TARGET_PROFILE_PATH=${AA_BUILD_OUT}

      # These are defined in the arch-specific docker-compose files
      #   - PLATFORM_BASE_IMAGE=ubuntu:jammy
      #   - LIBSSL_PKG_NAME=libssl3

      # The build platform is defined in the arch specific
      # docker-compose.{arch}.yaml files
      # x-bake:
      #   platforms:
      #     - linux/amd64

  # TODO: This is only appropriate in staging environments. Remove before we
  # go live.
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
