# This is built as

FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main

ARG CROSS_DEB_ARCH

# Change the packages to your dependencies.
COPY docker/tflite_prebuild.aarch64.sh /
ENV XDG_CACHE_HOME /home/cross
RUN apt-get install --assume-yes --no-install-recommends \
    apt-utils libssl-dev apt-transport-https gnupg \
    vim # For xxd
RUN dpkg --add-architecture $CROSS_DEB_ARCH
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get --assume-yes install \
    libgstreamer1.0-dev:$CROSS_DEB_ARCH \
    gstreamer1.0-plugins-base:$CROSS_DEB_ARCH \
    gstreamer1.0-plugins-good:$CROSS_DEB_ARCH \
    gstreamer1.0-plugins-bad:$CROSS_DEB_ARCH \
    gstreamer1.0-plugins-ugly:$CROSS_DEB_ARCH \
    gstreamer1.0-libav:$CROSS_DEB_ARCH \
    libgstrtspserver-1.0-dev:$CROSS_DEB_ARCH \
    libges-1.0-dev:$CROSS_DEB_ARCH \
    libssl-dev:$CROSS_DEB_ARCH
RUN DEBIAN_FRONTEND=noninteractive /tflite_prebuild.aarch64.sh
