# This file overrides the values found in docker-compose.yaml.
#
# NOTE:
# Do not call `docker compose` on this file directly, as it needs work done
# beforehand to build the software correctly.
#
# The `Hakufile` in the workspace root has everything you're looking for.
services:
  aa_app:
    platform: "linux/arm64"
    build:
      args:
        - PLATFORM_BASE_IMAGE=balenalib/raspberrypi4-64-debian:bullseye-run
        - LIBSSL_PKG_NAME=libssl1.1

      x-bake:
        platforms:
          - linux/arm64

  # TODO: Re-enable when we've got the Coral in hand.
  #  deploy:
  #    resources:
  #      reservations:
  #        devices:
  #          - capabilities: ["tpu"]

  # Watches the container repository for new versions of our images, updating
  # them as necessary.
  #
  # TODO: This is only appropriate in staging environments. Remove before we
  # go live.
  watchtower:
    image: containrrr/watchtower:arm64v8-latest
    platform: "linux/arm64"
