[build]
target = "x86_64-unknown-linux-gnu"

[profile.dev.build-override]
debug = 1
opt-level = 2

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[term]
quiet = false            # whether cargo output is quiet
verbose = true           # whether cargo provides verbose output
color = 'always'         # whether cargo colorizes output
progress.when = 'always' # whether cargo shows progress bar
progress.width = 80      # width of progress bar
