
parasolid_root_path = "para/"
stl_root_path = "stl/"

[document]
id = "85622754e9b97bcf5c74da64"
workspace_id = "5cb1ec8616ae905770ba618f"

# Small pan drive
[[assemblies]]
display_name = "unified"
id = "f1bba6743988c9e102b2513a"
synced_parts = [
  { basename = "camera_case", id = "MeEowqYxBtKWmxfBo" },
  { basename = "hardware_frame", id = "MZY/77GhjALfbx5lj" },
  { basename = "main_plate", id = "MZ6rZe9PHBMbINV1E" },
  { basename = "pan_drive_gear", id = "M8RGUGyaq6fbhJgGv" },
  { basename = "pan_inner_bearing_anchor", id = "MJAdTuw/XP+eW74ge" },
  { basename = "pan_outer_bearing_anchor", id = "MfaG3NqNY2BnCUE3h" },
  { basename = "pan_plate", id = "MdMsKWhqnBpOZyUoA" },
  { basename = "pan_reduction_gear", id = "MycgrKfujTgq2uC9d" },
  { basename = "ssd_clip", id = "MUMuSM9OdT82kSyvm" },
  { basename = "tilt_drive_collar", id = "MTQY4G7vG70f7sAqb" },
  { basename = "tilt_drive_shaft", id = "MvQnbGXa4wzj0MsU6" },
  { basename = "tilt_drive_gear", id = "MwywZoPvMcCGd8sCn" },
  { basename = "tilt_reduction_collar", id = "MqeUjOI41iK9CoX0f" },
  { basename = "tilt_reduction_shaft", id = "MCqdf57fWdZo/ZdFq" },
  { basename = "tilt_reduction_gear", id = "MuP4yCL8rorj7UXfs" },
  { basename = "tripod_connector", id = "MAdn6+vpN17/rYnks" },
]
