stl_root_path = "stl/"

[document]
id = "85622754e9b97bcf5c74da64"
workspace_id = "5cb1ec8616ae905770ba618f"

# Pan drive
[[assemblies]]
id = "319b8ad55c6e8f6cfd1daa19"
synced_parts = [
  { name = "lower_bottom", id = "MDiIkEUJrRZPHbnEa" },
  { name = "lower_top", id = "M8b+GG8MFp049yPbQ" },
  { name = "mount_plate", id = "MKzWAY9BOvk6nl2/N" },
  { name = "pan_drive_gear", id = "MB5sz3viA9Yqv381r" },
  { name = "upper_base", id = "M4Asklq39duwC3evr" },
]
