stl_root_path = "stl/"

[document]
id = "85622754e9b97bcf5c74da64"
workspace_id = "5cb1ec8616ae905770ba618f"

# Small pan drive
[[assemblies]]
display_name = "unified"
id = "f1bba6743988c9e102b2513a"
synced_parts = [
  { basename = "tripod_connector", id = "MAdn6+vpN17/rYnks" },
  { basename = "pan_reduction_gear", id = "MRngRc8x3laJSyWum" },
  { basename = "pan_drive_gear", id = "MeGykTzvUwQ416Wii" },
]
