stl_root_path = "stl/"

[document]
id = "85622754e9b97bcf5c74da64"
workspace_id = "5cb1ec8616ae905770ba618f"

# Small pan drive
[[assemblies]]
display_name = "small pan drive"
id = "358259f70b396d03bfa3704b"
synced_parts = [
  { basename = "tripod_connector", id = "MzMNLUXwq2k6SLqBD" },
  { basename = "base_plate", id = "M9fzpGG4eLMVspctA" },
]
