[package]
name = "scratch"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
image = "0.24.5"
once_cell = "1.16.0"

[dev-dependencies.palette]
git = "https://github.com/Ogeon/palette"
rev = "2c69f1c"
features = ["std"]
